language: cpp
compiler: gcc
dist: trusty

before_install:
  - cd llmerge
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

script: 
  - g++ llmerge.cpp -std=c++11 -o llmerge11
  - g++ llmerge.cpp -std=c++14 -o llmerge14
  - g++ llmerge.cpp -std=c++17 -o llmerge17
  - g++ llmerge.cpp -std=c++11 -O2 -o llmerge1O2
